name: "Prebuild Binaries"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'     
        required: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
          windows-x86_64,
        ]
        include:
          - name: windows-x86_64
            os: windows-2019

    steps: 
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 19.x

    - name: Windows - Prebuild Binaries
      if: runner.os == 'Windows'
      shell: bash
      run: |
        npm install --ignore-scripts 
        node .prebuild/build.js 
        node_modules/.bin/prebuild -t 19.0.0 --include-regex "\.(node|exe|dll|pdb)" -r electron 

    - uses: AButler/upload-release-assets@v2.0
      with:
        files: 'prebuilds/*.tar.gz'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release-tag: ${{ github.event.inputs.tag }}
